// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sloywoijtrcihqlwjrrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsb3l3b2lqdHJjaWhxbHdqcnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzgyMzgsImV4cCI6MjA3MzQ1NDIzOH0.YKQ2cs6CVMqYsDOvd-8_jdNux9yqL-GGuYC0xhEazSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});